/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'followupsToday' : bigint,
  'totalLeads' : bigint,
  'closedLeads' : bigint,
  'siteVisitsPlanned' : bigint,
}
export interface Disposition {
  'id' : bigint,
  'status' : string,
  'createdAt' : bigint,
  'leadId' : bigint,
  'notes' : string,
  'followupDate' : string,
  'dateTime' : string,
}
export interface Lead {
  'id' : bigint,
  'status' : string,
  'propertyType' : string,
  'createdAt' : bigint,
  'fullName' : string,
  'preferredLocation' : string,
  'notes' : string,
  'leadSource' : string,
  'phone' : string,
  'nextFollowupDate' : string,
  'budget' : string,
}
export interface _SERVICE {
  'addDisposition' : ActorMethod<
    [bigint, string, string, string, string],
    Disposition
  >,
  'addLead' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    Lead
  >,
  'deleteLead' : ActorMethod<[bigint], boolean>,
  'getDashboardStats' : ActorMethod<[string], DashboardStats>,
  'getDispositions' : ActorMethod<[bigint], Array<Disposition>>,
  'getLead' : ActorMethod<[bigint], Lead>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getOverdueLeads' : ActorMethod<[string], Array<Lead>>,
  'getRecentLeads' : ActorMethod<[], Array<Lead>>,
  'getTodayFollowups' : ActorMethod<[string], Array<Lead>>,
  'updateLead' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    Lead
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];