/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Disposition = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'leadId' : IDL.Nat,
  'notes' : IDL.Text,
  'followupDate' : IDL.Text,
  'dateTime' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'propertyType' : IDL.Text,
  'createdAt' : IDL.Int,
  'fullName' : IDL.Text,
  'preferredLocation' : IDL.Text,
  'notes' : IDL.Text,
  'leadSource' : IDL.Text,
  'phone' : IDL.Text,
  'nextFollowupDate' : IDL.Text,
  'budget' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'followupsToday' : IDL.Nat,
  'totalLeads' : IDL.Nat,
  'closedLeads' : IDL.Nat,
  'siteVisitsPlanned' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addDisposition' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Disposition],
      [],
    ),
  'addLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Lead],
      [],
    ),
  'deleteLead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
  'getDispositions' : IDL.Func([IDL.Nat], [IDL.Vec(Disposition)], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [Lead], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getOverdueLeads' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'getRecentLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getTodayFollowups' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'updateLead' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Lead],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Disposition = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'leadId' : IDL.Nat,
    'notes' : IDL.Text,
    'followupDate' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'propertyType' : IDL.Text,
    'createdAt' : IDL.Int,
    'fullName' : IDL.Text,
    'preferredLocation' : IDL.Text,
    'notes' : IDL.Text,
    'leadSource' : IDL.Text,
    'phone' : IDL.Text,
    'nextFollowupDate' : IDL.Text,
    'budget' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'followupsToday' : IDL.Nat,
    'totalLeads' : IDL.Nat,
    'closedLeads' : IDL.Nat,
    'siteVisitsPlanned' : IDL.Nat,
  });
  
  return IDL.Service({
    'addDisposition' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Disposition],
        [],
      ),
    'addLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Lead],
        [],
      ),
    'deleteLead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
    'getDispositions' : IDL.Func([IDL.Nat], [IDL.Vec(Disposition)], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [Lead], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getOverdueLeads' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
    'getRecentLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getTodayFollowups' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
    'updateLead' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Lead],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };